package gov.healthit.chpl.search.domain;

public enum OrderByOption {
    EDITION,
    DERIVED_EDITION,
    DEVELOPER,
    PRODUCT,
    VERSION,
    CERTIFICATION_DATE,
    CHPL_ID,
    STATUS,
    OPEN_SURVEILLANCE_NC_COUNT,
    CLOSED_SURVEILLANCE_NC_COUNT,
    OPEN_DIRECTREVIEW_NC_COUNT,
    CLOSED_DIRECTREVIEW_NC_COUNT;
}
